import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, ADMIN_USERNAME, ADMIN_EMAIL, ADMIN_TABLE, ADMIN_ID_COLUMN, UPDATES_TABLE, STORAGE_BUCKET } from '../supabase-config.js';
const db = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
const loginView = document.querySelector('#login-view');
const dashboard = document.querySelector('#dashboard-view');
const loginStatus = document.querySelector('#login-status');
const publishStatus = document.querySelector('#publish-status');
const posts = document.querySelector('#admin-posts');
const escapeHtml = (s='') => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function status(node,text,error=false){node.textContent=text;node.classList.toggle('error',error)}
async function isAdmin(user){const {data,error}=await db.from(ADMIN_TABLE).select(ADMIN_ID_COLUMN).eq(ADMIN_ID_COLUMN,user.id).maybeSingle();if(error)throw error;return Boolean(data)}
function enter(){loginView.hidden=true;dashboard.hidden=false;loadPosts()}
async function checkSession(){const {data:{session}}=await db.auth.getSession();if(!session?.user)return;try{if(await isAdmin(session.user))enter();else{await db.auth.signOut();status(loginStatus,'This account is not listed as an admin.',true)}}catch(e){status(loginStatus,`Admin lookup failed: ${e.message||'unknown database error'}. Check public.site_admins.user_id, SELECT grant and RLS policy.`,true)}}
document.querySelector('#login-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;status(loginStatus,'Checking login…');const f=new FormData(form);if(String(f.get('username')).trim().toUpperCase()!==ADMIN_USERNAME){status(loginStatus,'Username is incorrect.',true);return}const {data,error}=await db.auth.signInWithPassword({email:ADMIN_EMAIL,password:f.get('password')});if(error){status(loginStatus,'Login failed. Check your Supabase account password.',true);return}try{if(await isAdmin(data.user)){form.reset();enter()}else{await db.auth.signOut();status(loginStatus,'This user is not in site_admins. Access denied.',true)}}catch(err){await db.auth.signOut();status(loginStatus,`Admin verification failed: ${err.message||'unknown error'}. If this is a database permission error, check public.site_admins.user_id SELECT/RLS.`,true)}});
async function loadPosts(){posts.textContent='Loading…';const {data,error}=await db.from(UPDATES_TABLE).select('id,title,content,created_at').order('created_at',{ascending:false});if(error){posts.textContent='Could not load updates. Check table and admin RLS.';return}if(!data?.length){posts.textContent='No updates published yet.';return}posts.innerHTML=data.map(p=>`<article class="post"><div><small>${p.created_at?new Date(p.created_at).toLocaleDateString():'UPDATE'}</small><h3>${escapeHtml(p.title||'Update')}</h3><p>${escapeHtml(p.content||'')}</p></div><button type="button" data-id="${escapeHtml(p.id)}">Delete</button></article>`).join('');posts.querySelectorAll('[data-id]').forEach(button=>button.addEventListener('click',async()=>{if(!confirm('Delete this update?'))return;const {error:delError}=await db.from(UPDATES_TABLE).delete().eq('id',button.dataset.id);if(delError){status(publishStatus,'Delete failed. Check updates admin policy.',true);return}status(publishStatus,'Update deleted.');loadPosts()}))}
document.querySelector('#update-form').addEventListener('submit',async e=>{e.preventDefault();status(publishStatus,'Publishing…');const f=new FormData(e.currentTarget);const file=f.get('image');let imageUrl=String(f.get('image_url')||'').trim()||null;if(file?.size){const path=`${Date.now()}-${file.name.toLowerCase().replace(/[^a-z0-9._-]+/g,'-')}`;const {error:uploadError}=await db.storage.from(STORAGE_BUCKET).upload(path,file,{contentType:file.type});if(uploadError){status(publishStatus,`Image upload failed. Check the ${STORAGE_BUCKET} bucket or use an image URL.`,true);return}imageUrl=db.storage.from(STORAGE_BUCKET).getPublicUrl(path).data.publicUrl}const row={title:String(f.get('title')).trim(),content:String(f.get('content')).trim(),image_url:imageUrl,button_text:String(f.get('button_text')||'').trim()||null,button_url:String(f.get('button_url')||'').trim()||null};const {error}=await db.from(UPDATES_TABLE).insert(row);if(error){status(publishStatus,'Publish failed. Check updates columns and admin insert policy.',true);return}e.currentTarget.reset();status(publishStatus,'Update published.');loadPosts()});
document.querySelector('#sign-out').addEventListener('click',async()=>{await db.auth.signOut();dashboard.hidden=true;loginView.hidden=false;status(loginStatus,'Signed out.')});
checkSession();
d.hidden=true;loginView.hidden=false;status(loginStatus,'Signed out.')});
checkSession();
